# Generated by Django 3.0.6 on 2020-05-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('UID', models.AutoField(primary_key=True, serialize=False)),
                ('Department', models.CharField(max_length=50)),
                ('Grade', models.CharField(max_length=50)),
                ('Identity', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=50)),
                ('Comment', models.CharField(max_length=500)),
                ('phone', models.IntegerField(default=0)),
                ('Count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'comment',
            },
        ),
    ]
